#!/bin/sh

exec 2>&1

/usr/bin/warp-reg > /etc/warp.conf
WG_PRIVATE_KEY=$(grep private_key /etc/warp.conf | sed "s|.*: ||")
WG_PEER_PUBLIC_KEY=$(grep public_key /etc/warp.conf | sed "s|.*: ||")
WG_IP6_ADDR=$(grep v6 /etc/warp.conf | sed "s|.*: ||")
WG_RESERVED=$(grep reserved /etc/warp.conf | sed "s|.*: ||")
if [[ ! "${WG_RESERVED}" =~ , ]]; then
    WG_RESERVED=\"${WG_RESERVED}\"
fi

sed -i "s|WG_PRIVATE_KEY|${WG_PRIVATE_KEY}|;s|WG_PEER_PUBLIC_KEY|${WG_PEER_PUBLIC_KEY}|;s|fd00::1|${WG_IP6_ADDR}|;s|\[0, 0, 0\]|${WG_RESERVED}|" /workdir/config-wg.json



if [ "${VmessUUID}" = "" ]; then
    VmessUUID=ad2c9acd-3afb-4fae-aff2-954c532020bd
fi

cp -f /workdir/config-wg.json /tmp/config.json
sed -i "s|ad2c9acd-3afb-4fae-aff2-954c532020bd|${VmessUUID}|g;s|PASSWORD|${PASSWORD}|g;s|SecretPATH|${SecretPATH}|g;s|1408|${WG_MTU}|" /tmp/config.json

jq '.experimental.clash_api.default_mode |= "'"${CLASH_MODE}"'"' /tmp/config.json >./config.json
mv ./config.json /tmp/config.json

if [ "${OVERRIDE_DEST}" = "disable" ]; then
    sed -i "s|\"sniff_override_destination\": true|\"sniff_override_destination\": false|g" /tmp/config.json
fi

if [ ! "${BLOCK_QUIC_443}" = "true" ]; then
    jq 'del(.route.rules[1])' /tmp/config.json >./config.json
    mv ./config.json /tmp/config.json
fi

cd /usr/bin

exec ./app* run -c /tmp/config.json
